-- 코드를 입력하세요
WITH M AS (SELECT * FROM CART_PRODUCTS WHERE NAME = 'Milk')

SELECT distinct(CART_PRODUCTS.CART_ID) FROM CART_PRODUCTS, M
WHERE CART_PRODUCTS.NAME = 'Yogurt' AND CART_PRODUCTS.CART_ID IN (SELECT CART_ID FROM M)
ORDER BY CART_PRODUCTS.CART_ID