-- 코드를 작성해주세요
WITH SCORE AS (SELECT SUM(SKILLCODES.CODE) AS 'FRONT' FROM SKILLCODES WHERE CATEGORY = 'Front End')

SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME FROM DEVELOPERS D, SCORE S
WHERE D.SKILL_CODE & S.FRONT ORDER BY D.ID ASC