-- 코드를 작성해주세요
WITH CHILD AS (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY = 'RARE')

SELECT ITEM_INFO.ITEM_ID, ITEM_NAME, RARITY FROM ITEM_INFO JOIN ITEM_TREE ON ITEM_INFO.ITEM_ID = ITEM_TREE.ITEM_ID WHERE PARENT_ITEM_ID IN (SELECT ITEM_ID FROM CHILD) ORDER BY ITEM_INFO.ITEM_ID DESC
