-- 코드를 입력하세요
WITH  INFO AS (SELECT FLAVOR FROM ICECREAM_INFO WHERE INGREDIENT_TYPE = 'fruit_based')

SELECT F.FLAVOR FROM FIRST_HALF F WHERE F.TOTAL_ORDER > 3000 AND F.FLAVOR IN (SELECT FLAVOR FROM INFO)
ORDER BY F.TOTAL_ORDER DESC
