-- 코드를 입력하세요
SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, R.CREATED_DATE
FROM USED_GOODS_REPLY R LEFT JOIN USED_GOODS_BOARD B ON R.BOARD_ID = B.BOARD_ID
WHERE DATE_FORMAT(B.CREATED_DATE,'%Y') = '2022' AND DATE_FORMAT(B.CREATED_DATE, '%m') = '10'
ORDER BY R.CREATED_DATE, B.TITLE 